import type { GalleryItem } from '../../types'

// AUTO-GENERATED by scripts/fetch-instagram.mjs — do not edit by hand.
// This placeholder is replaced on the first successful sync:
//   pnpm fetch:instagram <username>

export const instagramProfile = { handle: '', profileUrl: 'https://www.instagram.com/' }

export const generatedInstagramPosts: GalleryItem[] = []